### ISSUE TITLE
0.1.5 升级 0.1.6 在 action 中失败

### ISSUE THREAD

**Issue by yinzixie** [lint-md/cli#10]
在本地没问题，结果 push 到 GitHub 后 action 中运行 check 命令时出错：
```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './lint'
Require stack:
- /home/runner/work/tastest-docs-web/tastest-docs-web/node_modules/@lint-md/cli/lib/lint-md.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/runner/work/tastest-docs-web/tastest-docs-web/node_modules/@lint-md/cli/lib/lint-md.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/tastest-docs-web/tastest-docs-web/node_modules/@lint-md/cli/lib/lint-md.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tastest-docs-web@1.0.0 check: `remark -f docs/ && lint-md docs/ && yamllint **/*.yml`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tastest-docs-web@1.0.0 check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-11-19T10_16_46_383Z-debug.log
Error: Process completed with exit code 1.
```

**Comment by yuzhanglong** [comment]
用的是 [GitHub Action](https://github.com/lint-md/github-action) 这个仓库吗？应该是我这边没有及时更新相关依赖。

**Comment by edalex-yinzi** [comment]
不是，我是直接用npm命令安装的。

**Comment by yuzhanglong** [comment]
> 不是，我是直接用 npm ci 命令安装的，然后跑 check 命令。

好的，我尝试修复下

**Comment by yuzhanglong** [comment]
> 不是，我是直接用 npm ci 命令安装的，然后跑 check 命令。

我这边没有遇到你这个情况，方便给一个具体的能复现的仓库吗？

**Comment by yuzhanglong** [comment]
已修复，是构建包大小写问题。
https://github.com/lint-md/cli/issues/11
https://github.com/lint-md/cli/pull/12
